# mysql:8
services:
  # nginx:
  #   image: ghcr.io/mikeiken/tam-prog-nginx:latest
  #   container_name: nginx
  #   networks:
  #     - gateway
  #   ports:
  #     - '${NGINX_HTTP_PORT}:80'
  #     - '${NGINX_HTTPS_PORT}:443'
  #   restart: always
  mysql:
    image: mysql:8
    container_name: mysql
    networks:
      - gateway
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    restart: always

  web:
    image: wp-lr3-web:latest
    container_name: web
    build: ./web
    networks:
      - gateway
    ports:
      - "${NODEJS_PORT}:3000"
    restart: always

  warehouse:
    image: wp-lr3-warehouse:latest
    container_name: warehouse
    build: ./warehouse
    volumes:
      - ./docker-data/warehouse/:/var/www
      - ./docker-data/warehouse/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${LARAVEL_PORT}:9000"

networks:
  gateway: {}